config/routes.rb
Couchbaseball::Application.routes.draw do

  
  resources :games
  resources :teams
  resources :seasons
  resources :team_season
  resources :people

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Game.by_season_team(:group_level => 1, :include_docs => false).fetch().reverse!
  end

  def show
    @season = params[:id]
    startkey = [ @season ]
    endkey = [@season, {} ]
    @seasonteams = Game.by_season_team(:group_level => 2, :include_docs => false, :startkey => startkey, :endkey => endkey)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/index.html.erb
<ul class="breadcrumb">  
  <li class="active">Seasons</li>  
</ul>

<h3>All Seasons</h3>

<table width="50%">
<tr>
  <th>Season</th>
  <th>Games</th>
</tr>
<% @seasons.each do |season| %>
  <tr>
    <td align="center"><%= link_to season.key[0], season_path(season.key[0]) %></td>
    <td align="center"><%= season.value/2%></td>
  </tr>
<% end %>
</table>

app/views/seasons/show.html.erb
<ul class="breadcrumb">
  <li>
    <%=link_to "Seasons", seasons_path()%> <span class="divider">></span>
  </li>    
  <li class="active"><%=@season%></li>  
</ul>

<h3>Season <%=@season%></h3>

<table width="50%">
<tr>
  <th>Team</th>
  <th>Games</th>
</tr>
<% @seasonteams.each do |seasonteam| %>
  <tr>
    <td align="center"><%= link_to seasonteam.key[1], team_season_path(seasonteam.key[1]+seasonteam.key[0]) %></td>
    <td align="center"><%= seasonteam.value%></td>
  </tr>
<% end %>
</table>